name: logsync-james
base: core18
version: '0.2'
summary: Enables upload of logs to a remote server
description: |
  Simple example snap to show how to send journal messages from a device
  to a remote journal server.

  To run the snap you need to connect a few interfaces and set a receiver url
  like below

  sudo snap connect logsync-james:daemon-notify
  sudo snap connect logsync-james:time-control
  sudo snap connect logsync-james:network-control
  sudo snap connect logsync-james:log-observe
  sudo snap set logsync-james url="http://<ip of the machine running logsync-receiver>"

grade: stable
confinement: strict

layout:
  /etc/systemd:
    bind: $SNAP_DATA/systemd

apps:
  upload:
    command: lib/systemd/systemd-journal-upload --save-state=$SNAP_DATA/state
    plugs:
      - daemon-notify
      - network-bind
      - network-control
      - network
      - log-observe
      - time-control # this quietens log spam at access of /proc/1/environ
    daemon: simple
    watchdog-timeout: 3m

parts:
  upload:
    plugin: nil
    stage-packages:
      - systemd-journal-remote
