name: logsync-james
base: core18
version: '0.2'
summary: Enables upload of logs to a remote server
description: |
  Simple example snap to show how to send journal messages from a device
  to a remote journal server.

grade: stable
confinement: strict

plugs:
  config-logsync:
    interface: system-files
    read:
      - /etc/systemd
    write:
      - /etc/systemd/journal-upload.conf

hooks:
  configure:
    plugs:
      - config-logsync

apps:
  upload:
    command: lib/systemd/systemd-journal-upload --save-state=$SNAP_DATA/state
    plugs:
      - network-bind
      - network
      - config-logsync
      - log-observe
    daemon: simple

parts:
  upload:
    plugin: nil
    stage-packages:
      - systemd-journal-remote
